#!/usr/bin/env python3
"""Summarise the graded corpus and regenerate CORPUS_INDEX.md."""

from __future__ import annotations

import collections
import json
from pathlib import Path

ARTIFACTS = Path(__file__).resolve().parents[2] / "artifacts" / "kernel-harden"
INDEX = ARTIFACTS / "CORPUS_INDEX.jsonl"
SUMMARY = ARTIFACTS / "CORPUS_INDEX.md"


def rows() -> list[dict]:
    if not INDEX.is_file():
        return []
    out = []
    for line in INDEX.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def _table(title: str, counts: collections.Counter) -> list[str]:
    lines = [f"## {title}", ""]
    lines += [f"- {key}: {value}" for key, value in sorted(counts.items(), key=lambda kv: str(kv[0]))]
    lines.append("")
    return lines


def render(data: list[dict]) -> str:
    completed = sum(1 for row in data if row.get("trace_path"))
    grades = collections.Counter(row.get("grade") for row in data)
    lines = [
        "# CORPUS_INDEX — Kernel harden",
        "",
        "Generated by `scripts/kernel_harden/count_corpus.py` from `CORPUS_INDEX.jsonl`.",
        "A row passes only when `unchecked` and `unchecked_reason` match the scenario's",
        "`expect` block; `skip` means the scenario assumes an absent optional provider",
        "that this machine has installed.",
        "",
        f"- scenarios: {len(data)}",
        f"- completed with trace: {completed}",
        f"- pass: {grades.get('pass', 0)} | fail: {grades.get('fail', 0)} | skip: {grades.get('skip', 0)}",
        "",
    ]
    lines += _table("By pack", collections.Counter(row.get("pack") for row in data))
    lines += _table("unchecked_reason", collections.Counter(row.get("unchecked_reason") for row in data))
    failures = [row for row in data if row.get("grade") == "fail"]
    if failures:
        lines += ["## Failures", ""]
        for row in failures:
            lines.append(
                f"- `{row['scenario_id']}` got "
                f"`{row['unchecked_reason']}` (unchecked={row['unchecked']}), expected "
                f"`{row['expected_reason']}` (unchecked={row['expected_unchecked']})"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    data = rows()
    SUMMARY.write_text(render(data), encoding="utf-8")
    grades = collections.Counter(row.get("grade") for row in data)
    completed = sum(1 for row in data if row.get("trace_path"))
    print(f"completed: {completed}")
    print(f"pass: {grades.get('pass', 0)} fail: {grades.get('fail', 0)} skip: {grades.get('skip', 0)}")


if __name__ == "__main__":
    main()
